
    import java.util.Scanner;
    import java.util.Random;

    class Task2_Number_Guessing_Game {

        public static void main(String[] args) {

            Scanner scanner = new Scanner(System.in);
            Random random = new Random();
            int randomNumber = random.nextInt(100) + 1; // Generating a random number between 1 and 100
            int userNumber;
            int attempts = 0;

            System.out.println("Welcome to 'Guess the Number' game! Try to guess the number generated by the computer between 1 and 100.");

            do {
                System.out.print("Enter your guess: ");
                userNumber = scanner.nextInt();
                attempts++;

                if (userNumber == randomNumber) {
                    System.out.println("Congratulations! You guessed the correct number. It took you " + attempts + " attempts.");
                } else if (userNumber > randomNumber) {
                    System.out.println("The number is lower. Try again.");
                } else {
                    System.out.println("The number is higher. Try again.");
                }
            } while (userNumber != randomNumber);

            scanner.close();
        }
    }

